---
apiVersion: v1
kind: Namespace
metadata:
  name: llm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: llm
  labels:
    app: ollama
spec:
  replicas: 2                   # Two replicas: one on each worker node
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      # Use nodeSelector to schedule pods only on worker nodes
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434       # Ollama API port inside the container
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: llm
spec:
  type: NodePort   # Suitable for bare metal clusters
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 80                 # Internal service port
      targetPort: 11434        # Container port
      nodePort: 30007          # External port on worker nodes (adjust if needed)
