apiVersion: v1
kind: Service
metadata:
  name: webui-service
  namespace: llm
spec:
  type: NodePort
  selector:
    app: gradio-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30081

