apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: llm
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080

